lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/test_full.config
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
  readme:
    - nextflow_badge
repository_type: pipeline
template:
  prefix: olc
  skip:
    - ci
    - github_badges
    - igenomes
